Implemented IsConstant Module
compiler-research/InterOp pull request #42
Opened 2023-03-14 08:49 UTC by Smit1603

- This PR will resolve issue #13 
- I have implemented and successfully tested IsConstant Module
- However there has been an unexpected hardware issue on my device so it has to be sent for servicing purpose, so it will be difficult for me to take up and resolve your issues/suggestions immediately
- Kindly review and pls let me know suggestions/improvements
- I would try to resolve and look over your suggestion as soon as possible 
- I am currently finding a way to continue being active and contribute

2023-03-14 10:17 UTC, vgvassilev commented on lib/Interpreter/InterOp.cpp
> +      return true;
```suggestion
    if (!method)
      return false;
    auto *D = (clang::Decl *)method;

    if (auto *func = dyn_cast<CXXMethodDecl>(D))
       return func->getMethodQualifiers().hasConst());
```

2023-03-14 10:51 UTC, vgvassilev commented
Please consider linking this PR with the opened issue in the commit message: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2023-03-20 21:58 UTC, Smit1603 commented
- @vgvassilev extremely sry for delay
- I have made recommended changes
- Pls review and let me know whether any other changes/Improvements are required or not

2023-03-22 22:04 UTC, vgvassilev commented on lib/Interpreter/InterOp.cpp
> +    //   return true;
Please delete the unused code. Also make all of this in one commit with a good commit message.

2023-03-23 14:47 UTC, sudo-panda requested changes

2023-03-23 14:47 UTC, sudo-panda commented on lib/Interpreter/InterOp.cpp
> +    auto *D = (clang::Decl *)method;
```suggestion
      return false;

    auto *D = (clang::Decl *)method;
```

2023-03-29 16:43 UTC, Smit1603 commented
- @vgvassilev 
- I have made all recommended changes
- I am facing similar issue as my last Pull Request(merge conflict) as you might know
- I am sorry I could not resolve this issue immediately, but is it possible for you to explain me how to resolve this issue on git so it might be a good learning experience for me as well as it will help me in future
- Sry for asking this silly question

2023-03-30 21:40 UTC, vgvassilev commented
I have fixed it.

2023-03-31 05:46 UTC, merged